import Spot from '../api/data/Spot';
import Extract from './Extract';
import TypedList from './TypedList';
import { PositionArray } from '@ephox/polaris';

/**
 * Finds an exact reference to a document point generated by Extract
 */
var find = function (universe, parent, offset, optimise) {
  var extractions = Extract.typed(universe, parent, optimise);

  var parray = PositionArray.generate(extractions, TypedList.gen);
  var spot = PositionArray.get(parray, offset);
  return spot.map(function (v) {
    return Spot.point(v.element(), offset - v.start());
  });
};

export default {
  find: find
};