enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  tiny-premium:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.tiny.cloud/"
  tinymce-dev:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.cloudsmith.io/tiny/tinymce-dev/"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
# npmScopes:
#   ephox:
#     npmRegistryServer: "https://registry.yarnpkg.com"
#   tinymce:
#     npmRegistryServer: "https://registry.yarnpkg.com"
