{
	"title": "tinymce.ui",
	"tests": [
		{"title": "AbsoluteLayout", "url": "AbsoluteLayout.html"},
		{"title": "Button", "url": "Button.html"},
		{"title": "ButtonGroup", "url": "ButtonGroup.html"},
		{"title": "Checkbox", "url": "Checkbox.html"},
		{"title": "Collection", "url": "Collection.html"},
		{"title": "ColorButton", "url": "ColorButton.html"},
		{"title": "ComboBox", "url": "ComboBox.html"},
		{"title": "Container", "url": "Container.html"},
		{"title": "Control", "url": "Control.html"},
		{"title": "DragHelper", "url": "DragHelper.html"},
		{"title": "ElementPath", "url": "ElementPath.html"},
		{"title": "Factory", "url": "Factory.html"},
		{"title": "FieldSet", "url": "FieldSet.html"},
		{"title": "FilePicker", "url": "FilePicker.html"},
		{"title": "FitLayout", "url": "FitLayout.html"},
		{"title": "FlexLayout", "url": "FlexLayout.html"},
		{"title": "FloatPanel", "url": "FloatPanel.html"},
		{"title": "FlowLayout", "url": "FlowLayout.html"},
		{"title": "Form", "url": "Form.html"},
		{"title": "FormItem", "url": "FormItem.html"},
		{"title": "GridLayout", "url": "GridLayout.html"},
		{"title": "Iframe", "url": "Iframe.html"},
		{"title": "KeyboardNavigation", "url": "KeyboardNavigation.html"},
		{"title": "Label", "url": "Label.html"},
		{"title": "Layout", "url": "Layout.html"},
		{"title": "ListBox", "url": "ListBox.html"},
		{"title": "Menu", "url": "Menu.html"},
		{"title": "MenuBar", "url": "MenuBar.html"},
		{"title": "MenuButton", "url": "MenuButton.html"},
		{"title": "MenuItem", "url": "MenuItem.html"},
		{"title": "MessageBox", "url": "MessageBox.html"},
		{"title": "Movable", "url": "Movable.html"},
		{"title": "Panel", "url": "Panel.html"},
		{"title": "PanelButton", "url": "PanelButton.html"},
		{"title": "Path", "url": "Path.html"},
		{"title": "Radio", "url": "Radio.html"},
		{"title": "Resizable", "url": "Resizable.html"},
		{"title": "ResizeHandle", "url": "ResizeHandle.html"},
		{"title": "Scrollable", "url": "Scrollable.html"},
		{"title": "Selector", "url": "Selector.html"},
		{"title": "Spacer", "url": "Spacer.html"},
		{"title": "SplitButton", "url": "SplitButton.html"},
		{"title": "StackLayout", "url": "StackLayout.html"},
		{"title": "TabPanel", "url": "TabPanel.html"},
		{"title": "TextBox", "url": "TextBox.html"},
		{"title": "Throbber", "url": "Throbber.html"},
		{"title": "Toolbar", "url": "Toolbar.html"},
		{"title": "Tooltip", "url": "Tooltip.html"},
		{"title": "Widget", "url": "Widget.html"},
		{"title": "Window", "url": "Window.html"}
	]
}
