tinyMCE.addI18n('en.advanced',{
style_select:"Styles",
font_size:"Font Size",
fontdefault:"Font Family",
block:"Format",
paragraph:"Paragraph",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code Sample",
dt:"Definition Term ",
dd:"Definition Description",
bold_desc:"Bold (Ctrl+B)",
italic_desc:"Italic (Ctrl+I)",
underline_desc:"Underline (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Align Left",
justifycenter_desc:"Align Center",
justifyright_desc:"Align Right",
justifyfull_desc:"Align Full",
bullist_desc:"Unordered List",
numlist_desc:"Ordered List",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Undo (Ctrl+Z)",
redo_desc:"Redo (Ctrl+Y)",
link_desc:"Insert/Edit Link",
unlink_desc:"Unlink",
image_desc:"Insert/Edit Image",
cleanup_desc:"Cleanup Messy Code",
code_desc:"Edit HTML Source",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Insert Horizontal Ruler",
removeformat_desc:"Remove Formatting",
custom1_desc:"Your custom description here",
forecolor_desc:"Select Text Color",
backcolor_desc:"Select Background Color",
charmap_desc:"Insert Custom Character",
visualaid_desc:"Toggle Guidelines/Invisible Elements",
anchor_desc:"Insert/Edit Anchor",
cut_desc:"Cut",
copy_desc:"Copy",
paste_desc:"Paste",
image_props_desc:"Image Properties",
newdocument_desc:"New Document",
help_desc:"Help",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More Colors",

// Accessibility Strings
shortcuts_desc:'Accessibility Help',
help_shortcut:'. Press ALT F10 for toolbar. Press ALT 0 for help.',
rich_text_area:"Rich Text Area",
toolbar:"Toolbar"
});
