tinymce.addI18n('id',{
"Cut": "Penggal",
"Heading 5": "Judul 5",
"Header 2": "Judul 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser anda tidak mendukung akses langsung ke clipboard. Silahkan gunakan Ctrl+X\/C\/V dari keyboard.",
"Heading 4": "Judul 4",
"Div": "Div",
"Heading 2": "Judul 2",
"Paste": "Tempel",
"Close": "Tutup",
"Font Family": "Jenis Huruf",
"Pre": "Pre",
"Align right": "Rata kanan",
"New document": "Dokumen baru",
"Blockquote": "Kutipan",
"Numbered list": "Daftar bernomor",
"Heading 1": "Judul 1",
"Headings": "Judul",
"Increase indent": "Tambah inden",
"Formats": "Format",
"Headers": "Judul",
"Select all": "Pilih semua",
"Header 3": "Judul 3",
"Blocks": "Blok",
"Undo": "Batal",
"Strikethrough": "Coret",
"Bullet list": "Daftar bersimbol",
"Header 1": "Judul 1",
"Superscript": "Superskrip",
"Clear formatting": "Hapus format",
"Font Sizes": "Ukuran Huruf",
"Subscript": "Subskrip",
"Header 6": "Judul 6",
"Redo": "Ulang",
"Paragraph": "Paragraf",
"Ok": "Ok",
"Bold": "Tebal",
"Code": "Kode",
"Italic": "Miring",
"Align center": "Rata tengah",
"Header 5": "Judul 5",
"Heading 6": "Judul 6",
"Heading 3": "Judul 3",
"Decrease indent": "Turunkan inden",
"Header 4": "Judul 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Penempelan sekarang dalam modus teks biasa. Konten sekarang akan disisipkan sebagai teks biasa sampai Anda memadamkan pilihan ini.",
"Underline": "Garis bawah",
"Cancel": "Batal",
"Justify": "Penuh",
"Inline": "Baris",
"Copy": "Salin",
"Align left": "Rata kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Huruf Kecil Yunani",
"Square": "Kotak",
"Default": "Bawaan",
"Lower Alpha": "Huruf Kecil",
"Circle": "Lingkaran",
"Disc": "Cakram",
"Upper Alpha": "Huruf Besar",
"Upper Roman": "Huruf Besar Romawi",
"Lower Roman": "Huruf Kecil Romawi",
"Name": "Nama",
"Anchor": "Jangkar",
"You have unsaved changes are you sure you want to navigate away?": "Anda memiliki perubahan yang belum disimpan, yakin ingin beralih ?",
"Restore last draft": "Muat kembali draft sebelumnya",
"Special character": "Spesial karakter",
"Source code": "Kode sumber",
"B": "B",
"R": "M",
"G": "H",
"Color": "Warna",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Properti dokumwn",
"Title": "Judul",
"Keywords": "Kata kunci",
"Encoding": "Enkoding",
"Description": "Deskripsi",
"Author": "Penulis",
"Fullscreen": "Layar penuh",
"Horizontal line": "Garis horisontal",
"Horizontal space": "Spasi horisontal",
"Insert\/edit image": "Sisip\/sunting gambar",
"General": "Umum",
"Advanced": "Lanjutan",
"Source": "Sumber",
"Border": "Batas",
"Constrain proportions": "Samakan proporsi",
"Vertical space": "Spasi vertikal",
"Image description": "Deskripsi gambar",
"Style": "Gaya",
"Dimensions": "Dimensi",
"Insert image": "Sisipkan gambar",
"Zoom in": "Perbesar",
"Contrast": "Kontras",
"Back": "Kembali",
"Gamma": "Gamma",
"Flip horizontally": "Balik horisontal",
"Resize": "Ubah ukuran",
"Sharpen": "Ketajaman",
"Zoom out": "Perkecil",
"Image options": "Opsi gambar",
"Apply": "Terapkan",
"Brightness": "Kecerahan",
"Rotate clockwise": "Putar searahjarumjam",
"Rotate counterclockwise": "Putar berlawananjarumjam",
"Edit image": "Sunting gambar",
"Color levels": "Tingakt warna",
"Crop": "Krop",
"Orientation": "Orientasi",
"Flip vertically": "Balik vertikal",
"Invert": "Kebalikan",
"Insert date\/time": "Sisipkan tanggal\/waktu",
"Remove link": "Buang tautan",
"Url": "Tautan",
"Text to display": "Teks yang ditampilkan",
"Anchors": "Jangkar",
"Insert link": "Sisipkan tautan",
"New window": "Jendela baru",
"None": "Tidak ada",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Tautan yang anda masukkan sepertinya adalah tautan eksternal. Apakah Anda ingin menambahkan prefiks http:\/\/ yang dibutuhkan?",
"Target": "Jendela tujuan",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Tautan yang anda masukkan sepertinya adalah alamat email. Apakah Anda ingin menambahkan prefiks mailto: yang dibutuhkan?",
"Insert\/edit link": "Sisip\/sunting tautan",
"Insert\/edit video": "Sisip\/sunting video",
"Poster": "Penulis",
"Alternative source": "Sumber alternatif",
"Paste your embed code below:": "Tempel kode yang diembed dibawah ini:",
"Insert video": "Sisipkan video",
"Embed": "Embed",
"Nonbreaking space": "Spasi",
"Page break": "Baris baru",
"Paste as text": "Tempel sebagai teks biasa",
"Preview": "Pratinjau",
"Print": "Cetak",
"Save": "Simpan",
"Could not find the specified string.": "Tidak dapat menemukan string yang dimaksud.",
"Replace": "Ganti",
"Next": "Berikutnya",
"Whole words": "Semua kata",
"Find and replace": "Cari dan ganti",
"Replace with": "Ganti dengan",
"Find": "Cari",
"Replace all": "Ganti semua",
"Match case": "Samakan besar kecil huruf",
"Prev": "Sebelumnya",
"Spellcheck": "Periksa ejaan",
"Finish": "Selesai",
"Ignore all": "Abaikan semua",
"Ignore": "Abaikan",
"Add to Dictionary": "Tambahkan ke kamus",
"Insert row before": "Sisipkan baris sebelum",
"Rows": "Baris",
"Height": "Tinggi",
"Paste row after": "Tempel baris setelah",
"Alignment": "Penjajaran",
"Border color": "Warna batas",
"Column group": "Kelompok kolom",
"Row": "Baris",
"Insert column before": "Sisipkan kolom sebelum",
"Split cell": "Bagi sel",
"Cell padding": "Lapisan sel",
"Cell spacing": "Spasi sel ",
"Row type": "Tipe baris",
"Insert table": "Sisipkan tabel",
"Body": "Body",
"Caption": "Caption",
"Footer": "Footer",
"Delete row": "Hapus baris",
"Paste row before": "Tempel baris sebelum",
"Scope": "Skup",
"Delete table": "Hapus tabel",
"H Align": "Rata Samping",
"Top": "Atas",
"Header cell": "Judul sel",
"Column": "Kolom",
"Row group": "Kelompok baris",
"Cell": "Sel",
"Middle": "Tengah",
"Cell type": "Tipe sel",
"Copy row": "Salin baris",
"Row properties": "Properti baris",
"Table properties": "Properti tabel",
"Bottom": "Bawah",
"V Align": "Rata Atas",
"Header": "Judul",
"Right": "Kanan",
"Insert column after": "Sisipkan kolom setelah",
"Cols": "Kolom",
"Insert row after": "Sisipkan baris setelah",
"Width": "Lebar",
"Cell properties": "Properti sel",
"Left": "Kiri",
"Cut row": "Penggal baris",
"Delete column": "Hapus kolom",
"Center": "Tengah",
"Merge cells": "Gabung sel",
"Insert template": "Sisipkan templat",
"Templates": "Templat",
"Background color": "Warna latar",
"Custom...": "Atur sendiri...",
"Custom color": "Warna sendiri",
"No color": "Tidak berwarna",
"Text color": "Warna teks",
"Show blocks": "Tampilkan blok",
"Show invisible characters": "Tampilkan karakter tak tampak",
"Words: {0}": "Kata: {0}",
"Insert": "Sisip",
"File": "Berkas",
"Edit": "Sunting",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area teks kaya. Tekan ALT-F9 untuk menu. Tekan ALT-F10 untuk toolbar. Tekan ALT-0 untuk bantuan",
"Tools": "Alat",
"View": "Tampilan",
"Table": "Tabel",
"Format": "Format"
});