tinymce.addI18n('is_IS',{
"Cut": "Skera",
"Heading 5": "Fyrirs\u00f6gn 5",
"Header 2": "Fyrirs\u00f6gn 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Vafrinn \u00feinn sty\u00f0ur ekki beinann a\u00f0gang a\u00f0 klippibor\u00f0inu.  Nota\u00f0u Ctrl-X\/C\/V \u00e1 lyklabor\u00f0inu \u00ed sta\u00f0inn.",
"Heading 4": "Fyrirs\u00f6gn 4",
"Div": "Div",
"Heading 2": "Fyrirs\u00f6gn 2",
"Paste": "L\u00edma",
"Close": "Loka",
"Font Family": "Letur fj\u00f6lskylda",
"Pre": "\u00d3st\u00edla\u00f0",
"Align right": "H\u00e6grijafna",
"New document": "N\u00fdtt skjal",
"Blockquote": "Blokk",
"Numbered list": "N\u00famera\u00f0ur listi",
"Heading 1": "Fyrirs\u00f6gn 1",
"Headings": "Fyrirsagnir",
"Increase indent": "Auka inndr\u00e1tt",
"Formats": "Sni\u00f0m\u00e1t",
"Headers": "Fyrirsagnir",
"Select all": "Velja allt",
"Header 3": "Fyrirs\u00f6gn 3",
"Blocks": "Blokkir",
"Undo": "Afturkalla",
"Strikethrough": "Yfirstrika\u00f0",
"Bullet list": "K\u00falu listi",
"Header 1": "Fyrirs\u00f6gn 1",
"Superscript": "Uppskrift",
"Clear formatting": "Hreinsa sni\u00f0",
"Font Sizes": "Leturst\u00e6r\u00f0",
"Subscript": "Ni\u00f0urskrifa\u00f0",
"Header 6": "Fyrirs\u00f6gn 6",
"Redo": "Endurkalla",
"Paragraph": "M\u00e1lsgrein",
"Ok": "Sta\u00f0festa",
"Bold": "Feitletra\u00f0",
"Code": "K\u00f3\u00f0i",
"Italic": "Skr\u00e1letra\u00f0",
"Align center": "Mi\u00f0jujafna",
"Header 5": "Fyrirs\u00f6gn 5",
"Heading 6": "Fyrirs\u00f6gn 6",
"Heading 3": "Fyrirs\u00f6gn 3",
"Decrease indent": "Minnka inndr\u00e1tt",
"Header 4": "Fyrirs\u00f6gn 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "L\u00edming er \u00ed l\u00e1tlausum ham.  Innihald ver\u00f0ur l\u00edmt sem l\u00e1tlaus texti \u00feanga\u00f0 til \u00fe\u00fa afvirkjar \u00feennan m\u00f6guleika.",
"Underline": "Undirstrika\u00f0",
"Cancel": "H\u00e6tta vi\u00f0",
"Justify": "Jafna",
"Inline": "Inndregi\u00f0",
"Copy": "Afrita",
"Align left": "Vinstrijafna",
"Visual aids": "Sj\u00f3nr\u00e6n hj\u00e1lp",
"Lower Greek": "L\u00e1gstafir Gr\u00edskir",
"Square": "Ferningur",
"Default": "Sj\u00e1lfgefi\u00f0",
"Lower Alpha": "L\u00e1gstafir Alpha",
"Circle": "Hringur",
"Disc": "Diskur",
"Upper Alpha": "H\u00e1stafir Alpha",
"Upper Roman": "H\u00e1stafir R\u00f3mverskir",
"Lower Roman": "L\u00e1gstafir R\u00f3mverskir",
"Name": "Nafn",
"Anchor": "Akkeri",
"You have unsaved changes are you sure you want to navigate away?": "\u00dea\u00f0 eru \u00f3vista\u00f0ar breytingar, ertu viss um a\u00f0 \u00fe\u00fa viljir vafra \u00ed burtu?",
"Restore last draft": "Endurkalla s\u00ed\u00f0asta uppkast",
"Special character": "S\u00e9rstakir stafir",
"Source code": "Frumk\u00f3\u00f0i",
"B": "B",
"R": "R",
"G": "G",
"Color": "Litur",
"Right to left": "H\u00e6gri til vinstri",
"Left to right": "Vinstri til h\u00e6gri",
"Emoticons": "Tilfinningar",
"Robots": "Leitarv\u00e9lar",
"Document properties": "Eigindi skjals",
"Title": "Titill",
"Keywords": "Lykilor\u00f0",
"Encoding": "Umbreyting",
"Description": "L\u00fdsing",
"Author": "H\u00f6fundur",
"Fullscreen": "Fylla skj\u00e1",
"Horizontal line": "L\u00e1r\u00e9tt l\u00edna",
"Horizontal space": "L\u00e1r\u00e9tt bil",
"Insert\/edit image": "Setja inn\/breyta mynd",
"General": "Almennt",
"Advanced": "\u00cdtarlegt",
"Source": "Sl\u00f3\u00f0i",
"Border": "Rammi",
"Constrain proportions": "Halda hlutf\u00f6llum",
"Vertical space": "L\u00f3\u00f0r\u00e9tt bil",
"Image description": "L\u00fdsing myndar",
"Style": "St\u00edll",
"Dimensions": "Hlutf\u00f6ll",
"Insert image": "Setja inn mynd",
"Zoom in": "\u00deysja inn",
"Contrast": "Contrast",
"Back": "Til baka",
"Gamma": "Gamma",
"Flip horizontally": "Sn\u00faa l\u00f3\u00f0r\u00e9tt",
"Resize": "Breyta st\u00e6r\u00f0",
"Sharpen": "Skerpa",
"Zoom out": "\u00deysja \u00fat",
"Image options": "Valm\u00f6guleikar myndar",
"Apply": "Sta\u00f0festa",
"Brightness": "Birtustig",
"Rotate clockwise": "Sn\u00faa r\u00e9tts\u00e6lis",
"Rotate counterclockwise": "Sn\u00faa rangs\u00e6lis",
"Edit image": "Breyta mynd",
"Color levels": "Litastu\u00f0lar",
"Crop": "Crop",
"Orientation": "Orientation",
"Flip vertically": "Sn\u00faa l\u00f3\u00f0r\u00e9tt",
"Invert": "Invert",
"Insert date\/time": "Setja inn dagsetningu\/t\u00edma",
"Remove link": "Fjarl\u00e6gja hlekk",
"Url": "Veffang",
"Text to display": "Texti til a\u00f0 s\u00fdna",
"Anchors": "Akkeri",
"Insert link": "Setja inn hlekk",
"New window": "N\u00fdr gluggi",
"None": "Ekkert",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Hlekkurinn sem \u00fe\u00fa rita\u00f0ir inn l\u00fdtur \u00fat fyrir a\u00f0 vera ytri hlekkur. Viltu b\u00e6ta vi\u00f0 forskeytinu http:\/\/ ?",
"Target": "Mi\u00f0",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Hlekkurinn sem \u00fe\u00fa rita\u00f0ir inn l\u00fdtur \u00fat fyrir a\u00f0 vera netfang. Viltu b\u00e6ta vi\u00f0 forskeytinu mailto: ?",
"Insert\/edit link": "Setja inn\/breyta hlekk",
"Insert\/edit video": "Setja inn\/fjarl\u00e6gja myndband",
"Poster": "Plakat",
"Alternative source": "Valkv\u00e6\u00f0ur frumk\u00f3\u00f0i",
"Paste your embed code below:": "L\u00edma frumk\u00f3\u00f0a fyrir ne\u00f0an:",
"Insert video": "Setja inn myndband",
"Embed": "Hengja vi\u00f0",
"Nonbreaking space": "Bil sem brotnar ekki",
"Page break": "S\u00ed\u00f0ubrot",
"Paste as text": "L\u00edma sem texta",
"Preview": "Forsko\u00f0un",
"Print": "Prenta",
"Save": "Vista",
"Could not find the specified string.": "Fann ekki umbe\u00f0inn streng.",
"Replace": "Skipta \u00fat",
"Next": "N\u00e6sti",
"Whole words": "Heil or\u00f0",
"Find and replace": "Finna og skipta \u00fat",
"Replace with": "Skipta \u00fat me\u00f0",
"Find": "Finna",
"Replace all": "Skipta \u00f6llum \u00fat",
"Match case": "Samanbur\u00f0ur",
"Prev": "Fyrri",
"Spellcheck": "Villuleit",
"Finish": "Lj\u00faka",
"Ignore all": "Hunsa allt",
"Ignore": "Hunsa",
"Add to Dictionary": "B\u00e6ta vi\u00f0 or\u00f0ab\u00f3k",
"Insert row before": "Setja inn r\u00f6\u00f0 fyrir framan",
"Rows": "Ra\u00f0ir",
"Height": "H\u00e6\u00f0",
"Paste row after": "L\u00edma r\u00f6\u00f0 fyrir aftan",
"Alignment": "J\u00f6fnun",
"Border color": "Litur \u00e1 ramma",
"Column group": "H\u00f3pur d\u00e1lks",
"Row": "R\u00f6\u00f0",
"Insert column before": "Setja inn d\u00e1lk fyrir framan",
"Split cell": "Deila reiti",
"Cell padding": "R\u00fdmi reits",
"Cell spacing": "Bil \u00ed reit",
"Row type": "Tegund ra\u00f0ar",
"Insert table": "Setja inn t\u00f6flu",
"Body": "Innihald",
"Caption": "Titill",
"Footer": "Ne\u00f0anm\u00e1l",
"Delete row": "Ey\u00f0a r\u00f6\u00f0",
"Paste row before": "L\u00edma r\u00f6\u00f0 fyrir framan",
"Scope": "Gildissvi\u00f0",
"Delete table": "Ey\u00f0a t\u00f6flu",
"H Align": "L\u00e1r\u00e9tt j\u00f6fnun",
"Top": "Efst",
"Header cell": "Reitarhaus",
"Column": "D\u00e1lkur",
"Row group": "H\u00f3pur ra\u00f0ar",
"Cell": "Reitur",
"Middle": "Mi\u00f0ja",
"Cell type": "Tegund reits",
"Copy row": "Afrita r\u00f6\u00f0",
"Row properties": "Stillingar ra\u00f0ar",
"Table properties": "Stillingar t\u00f6flu",
"Bottom": "Ne\u00f0st",
"V Align": "L\u00f3\u00f0r\u00e9tt j\u00f6fnun",
"Header": "Fyrirs\u00f6gn",
"Right": "H\u00e6gri",
"Insert column after": "Setja inn d\u00e1lk fyrir aftan",
"Cols": "D\u00e1lkar",
"Insert row after": "Setja inn r\u00f6\u00f0 fyrir aftan",
"Width": "Breidd",
"Cell properties": "Stillingar reits",
"Left": "Vinstri",
"Cut row": "Klippa r\u00f6\u00f0",
"Delete column": "Ey\u00f0a d\u00e1lki",
"Center": "Mi\u00f0ja",
"Merge cells": "Sameina reiti",
"Insert template": "Setja inn sni\u00f0m\u00e1t",
"Templates": "Sni\u00f0m\u00e1t",
"Background color": "Bakgrunnslitur",
"Custom...": "S\u00e9rsni\u00f0i\u00f0...",
"Custom color": "S\u00e9rsni\u00f0in litur",
"No color": "Enginn litur",
"Text color": "Litur texta",
"Show blocks": "S\u00fdna kubba",
"Show invisible characters": "S\u00fdna \u00f3s\u00fdnilega stafi",
"Words: {0}": "Or\u00f0:  {0}",
"Insert": "Setja inn",
"File": "Skjal",
"Edit": "Breyta",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Textasv\u00e6\u00f0i \u00ed \u00edtarham.  \u00ddttu \u00e1 ALT-F9 fyrir valmynd.  \u00ddttu \u00e1 ALT-F10 fyrir t\u00f3lastiku.  \u00ddttu \u00e1 ALT-0 fyrir a\u00f0sto\u00f0.",
"Tools": "T\u00f3l",
"View": "Sko\u00f0a",
"Table": "Tafla",
"Format": "Sni\u00f0"
});