tinymce.addI18n('oc',{
"Cut": "Talhar",
"Heading 5": "T\u00edtol 5",
"Header 2": "Ent\u00e8sta 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "V\u00f2stre navigador sup\u00f2rta pas la c\u00f2pia dir\u00e8cta. Merc\u00e9 d'utilizar las t\u00f2cas Ctrl+X\/C\/V.",
"Heading 4": "T\u00edtol 4",
"Div": "Div",
"Heading 2": "T\u00edtol 2",
"Paste": "Pegar",
"Close": "Tampar",
"Font Family": "Poli\u00e7a",
"Pre": "Pre",
"Align right": "Alinhar a drecha",
"New document": "Document nov\u00e8l",
"Blockquote": "Citacion",
"Numbered list": "Lista numerotada",
"Heading 1": "T\u00edtol 1",
"Headings": "T\u00edtols",
"Increase indent": "Aumentar l'alin\u00e8a",
"Formats": "Formats",
"Headers": "Ent\u00e8stas",
"Select all": "Seleccionar tot",
"Header 3": "Ent\u00e8sta 3",
"Blocks": "Bl\u00f2ts",
"Undo": "Desfar",
"Strikethrough": "Ralhat",
"Bullet list": "Piuses",
"Header 1": "Ent\u00e8sta 1",
"Superscript": "Exponent",
"Clear formatting": "Escafar la mesa en forma",
"Font Sizes": "Talhas de poli\u00e7a",
"Subscript": "Indici",
"Header 6": "Ent\u00e8sta 6",
"Redo": "Refar",
"Paragraph": "Paragraf",
"Ok": "D'ac\u00f2rdi",
"Bold": "Gras",
"Code": "C\u00f2de",
"Italic": "Italica",
"Align center": "Alinhar al centre",
"Header 5": "Ent\u00e8sta 5",
"Heading 6": "T\u00edtol 6",
"Heading 3": "T\u00edtol 3",
"Decrease indent": "Demesir l'alin\u00e8a",
"Header 4": "Ent\u00e8sta 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Lo quichapapi\u00e8rs es ara en m\u00f2de \"t\u00e8xte plen\". Los contenguts ser\u00e0n pegats sens ret\u00e9ner los formatatges fins al moment que desactivaretz aquesta opcion.",
"Underline": "Solinhat",
"Cancel": "Anullar",
"Justify": "Justificar",
"Inline": "En linha",
"Copy": "Copiar",
"Align left": "Alinhar a esqu\u00e8rra",
"Visual aids": "Ajudas visualas",
"Lower Greek": "Gr\u00e8c minuscula",
"Square": "Carrat",
"Default": "Per defaut",
"Lower Alpha": "Alfa minuscula",
"Circle": "Cercle",
"Disc": "Disc",
"Upper Alpha": "Alfa majuscula",
"Upper Roman": "Roman majuscula",
"Lower Roman": "Roman minuscula",
"Name": "Nom",
"Anchor": "Anc\u00f2ra",
"You have unsaved changes are you sure you want to navigate away?": "Av\u00e8tz de modificacions pas enregistradas, s\u00e8tz segur que vol\u00e8tz quitar la pagina ?",
"Restore last draft": "Restablir lo darri\u00e8r borrolhon",
"Special character": "Caract\u00e8r especial",
"Source code": "C\u00f2de font",
"B": "B",
"R": "R",
"G": "V",
"Color": "Color",
"Right to left": "De drecha cap a esqu\u00e8rra",
"Left to right": "D'esqu\u00e8rra cap a drecha",
"Emoticons": "Emotic\u00f2nas",
"Robots": "Rob\u00f2ts",
"Document properties": "Proprietats del document",
"Title": "T\u00edtol",
"Keywords": "Mots claus",
"Encoding": "Encodatge",
"Description": "Descripcion",
"Author": "Autor",
"Fullscreen": "Ecran complet",
"Horizontal line": "Linha orizontala",
"Horizontal space": "Espa\u00e7ament orizontal",
"Insert\/edit image": "Inserir\/modificar un imatge",
"General": "General",
"Advanced": "Avan\u00e7at",
"Source": "Font",
"Border": "Bordadura",
"Constrain proportions": "Conservar las proporcions",
"Vertical space": "Espa\u00e7ament vertical",
"Image description": "Descripcion de l'imatge",
"Style": "Estil",
"Dimensions": "Dimensions",
"Insert image": "Inserir un imatge",
"Zoom in": "Zoom avant",
"Contrast": "Contraste",
"Back": "Retorn",
"Gamma": "Gamma",
"Flip horizontally": "Revirament orizontal",
"Resize": "Redimensionar",
"Sharpen": "Afinar",
"Zoom out": "Zoom arri\u00e8r",
"Image options": "Opcions de l'imatge",
"Apply": "Aplicar",
"Brightness": "Luminositat",
"Rotate clockwise": "Rotacion or\u00e0ria",
"Rotate counterclockwise": "Rotacion anti-or\u00e0ria",
"Edit image": "Modificar l'imatge",
"Color levels": "Niv\u00e8ls de color",
"Crop": "Retalhar",
"Orientation": "Orientacion",
"Flip vertically": "Revirament vertical",
"Invert": "Inversar",
"Insert date\/time": "Inserir data\/ora",
"Remove link": "Suprimir lo ligam",
"Url": "Url",
"Text to display": "T\u00e8xte d'afichar",
"Anchors": "Anc\u00f2ras",
"Insert link": "Inserir un ligam",
"New window": "Fen\u00e8stra nov\u00e8la",
"None": "Pas cap",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Sembla que l'URL qu'av\u00e8tz entrada es un ligam ext\u00e8rne. Vol\u00e8tz apondre lo prefix http:\/\/ necessari ?",
"Target": "Cibla",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Sembla que l'URL qu'av\u00e8tz entrada es una adre\u00e7a e-mail. Vol\u00e8tz apondre lo prefix mailto: necessari ?",
"Insert\/edit link": "Inserir\/modificar un ligam",
"Insert\/edit video": "Inserir\/modificar una vid\u00e8o",
"Poster": "Publicar",
"Alternative source": "Font alternativa",
"Paste your embed code below:": "Pegatz v\u00f2tre c\u00f2di d'integracion \u00e7aij\u00f3s :",
"Insert video": "Inserir una vid\u00e8o",
"Embed": "Integrat",
"Nonbreaking space": "Espaci insecable",
"Page break": "Pagina copada",
"Paste as text": "Pegar coma de t\u00e8xte",
"Preview": "Previsualizar",
"Print": "Imprimir",
"Save": "Enregistrar",
"Could not find the specified string.": "Impossible de trobar la cadena especificada.",
"Replace": "Rempla\u00e7ar",
"Next": "Seg",
"Whole words": "Mots enti\u00e8rs",
"Find and replace": "Recercar e rempla\u00e7ar",
"Replace with": "Rempla\u00e7ar per",
"Find": "Recercar",
"Replace all": "Rempla\u00e7ar tot",
"Match case": "Respectar la cassa",
"Prev": "Prec",
"Spellcheck": "Corrector ortografic",
"Finish": "Acabar",
"Ignore all": "Ignorar tot",
"Ignore": "Ignorar",
"Add to Dictionary": "Apondre al diccionari",
"Insert row before": "Inserir una linha abans",
"Rows": "Linhas",
"Height": "Nautor",
"Paste row after": "Pegar la linha apr\u00e8p",
"Alignment": "Alinhament",
"Border color": "Color de la bordadura",
"Column group": "Column group",
"Row": "Linha",
"Insert column before": "Inserir una colomna abans",
"Split cell": "Devesir la cellula",
"Cell padding": "Cell padding",
"Cell spacing": "Cell spacing",
"Row type": "Tipe de linha",
"Insert table": "Inserir un tabl\u00e8u",
"Body": "C\u00f2s",
"Caption": "Caption",
"Footer": "P\u00e8 de pagina",
"Delete row": "Suprimir la linha",
"Paste row before": "Pegar la linha abans",
"Scope": "Scope",
"Delete table": "Suprimir lo tabl\u00e8u",
"H Align": "H Align",
"Top": "Top",
"Header cell": "Header cell",
"Column": "Colomna",
"Row group": "Row group",
"Cell": "Cellula",
"Middle": "Mitan",
"Cell type": "Tipe de cellula",
"Copy row": "Copiar la linha",
"Row properties": "Proprietats de la linha",
"Table properties": "Proprietats del tabl\u00e8u",
"Bottom": "Bottom",
"V Align": "V Align",
"Header": "Ent\u00e8sta",
"Right": "Drecha",
"Insert column after": "Inserir una colomna apr\u00e8p",
"Cols": "Colomnas",
"Insert row after": "Inserir una linha apr\u00e8p",
"Width": "Largor",
"Cell properties": "Proprietats de la cellula",
"Left": "Esqu\u00e8rra",
"Cut row": "Talhar la linha",
"Delete column": "Suprimir la colomna",
"Center": "Centre",
"Merge cells": "Fusionar las cellulas",
"Insert template": "Inserir un mod\u00e8l",
"Templates": "Mod\u00e8ls",
"Background color": "Color de r\u00e8ireplan",
"Custom...": "Personalizar...",
"Custom color": "Color personalizada",
"No color": "Pas de color",
"Text color": "Color del t\u00e8xte",
"Show blocks": "Afichar los bl\u00f2ts",
"Show invisible characters": "Far veire los caract\u00e8rs invisibles",
"Words: {0}": "Mots : {0}",
"Insert": "Inserir",
"File": "Fichi\u00e8r",
"Edit": "Editar",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Z\u00f2na T\u00e8xte Ric. Quichar sus ALT-F9 pel men\u00fa. Quichar sus ALT-F10 per la barra d'aisinas. Quichar sus ALT-0 per d'ajuda.",
"Tools": "Aisinas",
"View": "Veire",
"Table": "Tabl\u00e8u",
"Format": "Format"
});