import { playwright } from '@vitest/browser-playwright';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

import { mousedownCommand, mousemoveCommand, mouseupCommand } from './vitest-custom-commands';

const oxideComponentsAlias = {
  find: 'oxide-components',
  replacement: fileURLToPath(new URL('./src/main/ts/', import.meta.url))
};

const visualBrowserProvider = playwright(
  process.env.PW_WS_ENDPOINT === undefined ? undefined : {
    connectOptions: {
      wsEndpoint: process.env.PW_WS_ENDPOINT,
      exposeNetwork: '<loopback>'
    }
  }
);

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'atomic',
          environment: 'node',
          server: {
            deps: {
              // @ephox/dispute ships "type": "module" with extensionless relative imports,
              // which Node's strict ESM loader rejects. Inlining routes @ephox packages
              // through Vite's resolver, which tolerates the missing extension. The whole
              // chain (sugar → katamari → dispute) must be inlined: if a parent stays
              // externalized, Node loads it directly and its `import '@ephox/dispute'`
              // never reaches Vite.
              inline: [ '@ephox' ]
            }
          },
          alias: [ oxideComponentsAlias ],
          include: [
            'src/test/ts/atomic/**/*.spec.ts'
          ]
        }
      },
      {
        optimizeDeps: {
          include: [ 'react/jsx-dev-runtime' ],
        },
        test: {
          name: 'browser',
          setupFiles: [ './vitest.setup.js' ],
          alias: [ oxideComponentsAlias ],
          include: [
            'src/test/ts/browser/**/*.spec.{ts,tsx}'
          ],
          // Visual specs are colocated with behavior specs but only run in the
          // `visual` project: they need Linux-rendered screenshots (Docker/CI).
          exclude: [ '**/*.visual.spec.{ts,tsx}' ],
          browser: {
            provider: playwright(),
            enabled: true,
            headless: true,
            screenshotFailures: false,
            instances: [
              { browser: 'chromium' }
            ],
            commands: { mousedownCommand, mouseupCommand, mousemoveCommand }
          }
        },
      },
      {
        optimizeDeps: {
          include: [ 'react/jsx-dev-runtime' ],
        },
        test: {
          name: 'visual',
          // Run test files sequentially: parallel files run in parallel pages of the
          // same browser, and window focus ping-pongs between them. Firefox (and to a
          // lesser extent WebKit) only paints `:focus`/`:focus-visible` styling and
          // other activation-dependent state into screenshots for the active page, so
          // parallel files make focus-state screenshots nondeterministic.
          fileParallelism: false,
          setupFiles: [ './vitest.setup.js' ],
          alias: [ oxideComponentsAlias ],
          include: [
            // Per-component visual specs, colocated with the behavior specs.
            'src/test/ts/**/*.visual.spec.{ts,tsx}'
          ],
          browser: {
            provider: visualBrowserProvider,
            enabled: true,
            headless: true,
            screenshotFailures: false,
            instances: [
              { browser: 'chromium', viewport: { width: 1280, height: 720 } },
              { browser: 'firefox', viewport: { width: 1280, height: 720 } },
              { browser: 'webkit', viewport: { width: 1280, height: 720 } }
            ],
            commands: { mousedownCommand, mouseupCommand, mousemoveCommand },
            expect: {
              toMatchScreenshot: {
                comparatorName: 'pixelmatch',
                comparatorOptions: {
                  allowedMismatchedPixelRatio: 0.02
                },
                // Stable-screenshot detection budget. Under CPU load (CI, busy dev
                // machine) individual captures are slow enough that the default 5s
                // cannot fit the required consecutive identical captures, failing
                // static renders with "could not capture a stable screenshot".
                timeout: 15_000,
                // Baselines are generated by Linux browsers via Docker/CI; omitting
                // process.platform prevents host OS names from splitting the baseline set.
                resolveScreenshotPath: ({ arg, browserName, ext, root, testFileDirectory }) =>
                  resolve(root, testFileDirectory, '__screenshots__', `${arg}-${browserName}${ext}`),
                resolveDiffPath: ({ arg, browserName, ext, root, attachmentsDir, testFileDirectory }) =>
                  resolve(root, attachmentsDir, testFileDirectory, '__screenshots__', `${arg}-${browserName}${ext}`)
              }
            }
          }
        },
      },
    ]
  },
});
