import { Node } from '@ephox/dom-globals';

const ATTRIBUTE = Node.ATTRIBUTE_NODE;
const CDATA_SECTION = Node.CDATA_SECTION_NODE;
const COMMENT = Node.COMMENT_NODE;
const DOCUMENT = Node.DOCUMENT_NODE;
const DOCUMENT_TYPE = Node.DOCUMENT_TYPE_NODE;
const DOCUMENT_FRAGMENT = Node.DOCUMENT_FRAGMENT_NODE;
const ELEMENT = Node.ELEMENT_NODE;
const TEXT = Node.TEXT_NODE;
const PROCESSING_INSTRUCTION = Node.PROCESSING_INSTRUCTION_NODE;
const ENTITY_REFERENCE = Node.ENTITY_REFERENCE_NODE;
const ENTITY = Node.ENTITY_NODE;
const NOTATION = Node.NOTATION_NODE;

export {
  ATTRIBUTE,
  CDATA_SECTION,
  COMMENT,
  DOCUMENT,
  DOCUMENT_TYPE,
  DOCUMENT_FRAGMENT,
  ELEMENT,
  TEXT,
  PROCESSING_INSTRUCTION,
  ENTITY_REFERENCE,
  ENTITY,
  NOTATION,
};