def credentialsId = '8aa93893-84cc-45fc-a029-a42f21197bb3'

node("primary") {
  def publishBuild = load("jenkins-plumbing/publish-build.groovy")

  stage ("Checkout project") {
    git([branch: "master", url:'ssh://git@stash:7999/tinymce/tinymce-mobile.git', credentialsId: credentialsId])
  }

  stage ("Fetch dependencies") {
    echo "Fetching npm dependencies"
    sh "rm -rf node_modules"
    sh "npm install"
  }
  
  stage ("Build TinyMCE project") {
    sh "grunt"
  }

  stage ("Build Mobile styles") {
    dir("src/themes/mobile") {
      sh "grunt less"
    }
  }

  stage ("Run Mobile tests") {
    dir("src/themes/mobile") {
      sh "grunt atomic-tests phantom-tests"
    }
  }

  stage ("Publishing Mobile theme") {
    step([$class: 'ArtifactArchiver', artifacts: 'dist/**'])
    publishBuild "dist"
  }
}