// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Popup',
events_tab : 'Events',
advanced_tab : 'Advanced',
general_props : 'General properties',
popup_props : 'Popup properties',
event_props : 'Events',
advanced_props : 'Advanced properties',
popup_opts : 'Options',
anchor_names : 'Anchors',
target_same : 'Open in this window / frame',
target_parent : 'Open in parent window / frame',
target_top : 'Open in top frame (replaces all frames)',
target_blank : 'Open in new window',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Window name',
popup_return : 'Insert \'return false\'',
popup_scrollbars : 'Show scrollbars',
popup_statusbar : 'Show status bar',
popup_toolbar : 'Show toolbars',
popup_menubar : 'Show menu bar',
popup_location : 'Show location bar',
popup_resizable : 'Make window resizable',
popup_dependent : 'Dependent (Mozilla/Firefox only)',
popup_size : 'Size',
popup_position : 'Position (X/Y)',
id : 'Id',
style: 'Style',
classes : 'Classes',
target_name : 'Target name',
langdir : 'Language direction',
target_langcode : 'Target language',
langcode : 'Language code',
encoding : 'Target character encoding',
mime : 'Target MIME type',
rel : 'Relationship page to target',
rev : 'Relationship target to page',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Left to right',
rtl : 'Right to left'
});
